#include "commander.h"
#include "commander_modules.h"   // generated by cmdr — run `cmdr module`

extern "C" CommanderConfig commander_config() {
    CommanderConfig cfg;
    cfg.uart_baud     = 115200;
    cfg.uart_greeting = "cmdr-unoq-ir-speaker";
    return cfg;
}

extern "C" void commander_setup(CommandRegistry& reg) {
    commander_register_modules(reg);
}
